name: Upload Encrypted Artifact
description: Encrypts file using provided passphrase, then uploads it
inputs:
  name:
    description: Name of file to upload
    required: true
  path:
    description: Path of file to upload
    required: true
  passphrase:
    description: Passphrase to encrypt file
    required: true
runs:
  using: composite
  steps:
    - name: encrypt file
      shell: bash
      run: gpg --symmetric --batch --yes --cipher-algo AES256 --passphrase ${{ inputs.passphrase }} --output ${{ inputs.path }}.gpg ${{ inputs.path }}
    - name: upload encrypted artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}.gpg
        retention-days: 1
    - name: remove encrypted artifact
      shell: bash
      run: rm -rf ${{ inputs.path }}.gpg && ls -la
