name: Test Encrypted Artifacts

on:
  workflow_call:
    inputs:
      name:
        description: Name of artifact
        required: true
      path:
        description: Path of file
        required: true
  workflow_dispatch:
    inputs:
      name:
        description: Name of artifact
        required: true
      path:
        description: Path of file
        required: true

jobs:
  upload-encrypted-artifact:
    name: Upload encrypted artifact
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: output kubeconfig to file
        shell: bash
        run: echo '${{ secrets.KUBE_CONFIG }}' > ${{ inputs.path }} && ls -la && cat ${{ inputs.path }}
      - name: Upload encrypted artifact
        uses: ./.github/actions/upload-encrypted-artifact
        with:
          name: ${{ inputs.name }}
          path: ${{ inputs.path }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

  download-encrypted-artifact:
    name: Download encrypted artifact
    environment: dev
    runs-on: ubuntu-latest
    needs: upload-encrypted-artifact
    steps:
      - uses: actions/checkout@v3
      - name: Download encrypted artifact
        uses: ./.github/actions/download-encrypted-artifact
        with:
          name: ${{ inputs.name }}
          path: ${{ inputs.path }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
