name: Test Encrypted Artifacts

on:
  workflow_dispatch:
    inputs:
      name:
        description: Name of file
        required: true
      path:
        description: Path of file
        required: true

jobs:
  upload-encrypted-artifact:
    name: Upload encrypted artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Upload encrypted artifact
        uses: ./.github/actions/upload-encrypted-artifact
        with:
          name: ${{ inputs.name }}
          path: ${{ inputs.path }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

  download-artifact:
    name: Download artifact
    runs-on: ubuntu-latest
    needs: upload-encrypted-artifact
    steps:
      - uses: actions/checkout@v3
      - name: Download encrypted artifact
        uses: ./.github/actions/download-encrypted-artifact
        with:
          name: ${{ inputs.name }}
          path: ${{ inputs.path }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

  upload-artifact:
    name: upload the decrypted artifact
    runs-on: ubuntu-latest
    needs: download-artifact
    steps:
      - uses: actions/checkout@v3
      - name: upload decrypted artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.name }}
          path: ${{ inputs.path }}
