name: Test Encrypted Artifacts

on:
  workflow_dispatch:
    inputs:
      name:
        description: Name of file to download
        required: true
      path:
        description: Path of file to download
        required: true

jobs:
  upload-artifact:
    name: Upload artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Upload encrypted artifact
        uses: ./.github/actions/upload-encrypted-artifact
        with:
          name: ${{ inputs.name }}
          path: ${{ inputs.path }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

  download-artifact:
    name: Download artifact
    runs-on: ubuntu-latest
    needs: upload-artifact
    steps:
      - uses: actions/checkout@v3
      - name: Download encrypted artifact
        uses: ./.github/actions/download-encrypted-artifact
        with:
          name: ${{ inputs.name }}
          path: ${{ inputs.path }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
